In [15]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import random

# Resampling with Kidney Disease Data

Today we will apply some of what we have been learning to the kidney disease data. The question we will ask is whether there is a significant difference in the means or medians of the two classes in our sample. This is equivalent to the two-population t-test in a traditional statistics class. Except our method works with other test statistics like the Median.

This approach is appropriate in cases where the dataset we have is a sample of a large population

In [43]:
# Let's continue exploring the penguins data set (our first Case Study that we will work on together)

kidney_url = 'https://drive.google.com/uc?export=download&id=1R8H9Hno1_fu7ON6yQlk9jNQsTXG6loup'
data_names = ['age', 'blood pressure', 'specific gravity', 'albumin', 'sugar',
            'red blood cells', 'pus cell', 'pus cell clumps', 'bacteria',
            'blood glucose random', 'blood urea', 'serum creatinine',
            'sodium', 'potassium', 'hemoglobin', 'packed cell volume',
            'white blood cell count', 'red blood cell count', 'hypertension',
            'diabetes mellitus', 'coronary artery disease', 'appetite',
            'pedal edema', 'anemia', 'class']

# use the na_values flag to parts the '?' as an NaN
kidney_data = pd.read_csv(kidney_url, names=data_names, na_values = ['?'])

# This is a large dataset, so we check by just displaying the first few rows using .head()
kidney_data.head()

,age,blood pressure,specific gravity,albumin,sugar,red blood cells,pus cell,pus cell clumps,bacteria,blood glucose random,...,packed cell volume,white blood cell count,red blood cell count,hypertension,diabetes mellitus,coronary artery disease,appetite,pedal edema,anemia,class
0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,121.0,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,NaN,...,38,6000,NaN,no,no,no,good,no,no,ckd
2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,423.0,...,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,117.0,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,106.0,...,35,7300,4.6,no,no,no,good,no,no,ckd

This example we should think of as a sample from a much larger population. That population would be patients who are in the hospital for symptoms that may indicate chronic kidney disease. 

1. You might recall the last time we worked with this dataset that the 'class' variable had some entries with some whitespace, fix this.

2. Choose one of the numerical variables to focus on and choose a test statistic (mean or median) to study: Be sure to both draw some visualizations of the distribtion of the data and to compute the numerical values for a test statistic. We will also need to know how many ckd and notcdk patients there are.

### Test Statistic

In this case, because the dataset is a sample of a larger population. The question we want to ask is was dividing that sample up into the two sets of ckd and notckd producing results for your numerical variable that are related to the ckd or was it just a result of random chance. To answer this we are going to do the following resampling experiment:

We will bootstrap the sample (sample it with replacement to rebuild it to the same size), which will introduce some randomness. Then divide it into two sets, one the size of the number of ckd patients in the original and the other the size of the number of notckd patients in the original and then ask what the difference in the means or medians of the two sets is.

3. In two you computed the means or medians. Compute their difference now to get the value of our test statistic in the original sample. 

4. (We can talk about how to do this together if you like):  Rewrite one of the experiment functions we have used before to do the following:

a. Take a random sample with replacement from your column that is the same size as the original sample.

b. Divide that sample into two sets one that is the size of the ckd in the original and one that is the size of the notckd in the original sample.

c. Compute the means or medians of each of those, and then the absolute value of the difference of those values. 

d. Add the result to a list or dataframe as the output for your function. 
    
5. Address the question. How frequently did we find that the difference in the means or medians was as large as in the original data set? Do we reject or accept the Null hypothesis for this variable?

6. Try to find an example with a sigificnat difference and an example without.